import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";

import HeaderHome from "@/components/layout/header-home";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Noi That NKT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* <ReduxProvider> */}
                {/* <ReduxPersistgate> */}
                <HeaderHome />
                <main>
                    {" "}
                    <AntdRegistry>{children}</AntdRegistry>
                </main>
                {/* </ReduxPersistgate> */}
                {/* </ReduxProvider> */}
            </body>
        </html>
    );
}
