import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavHome from "./components/navhome";

import ReduxProvider from "./components/reduxprovider";
import ReduxPersistgate from "./components/persistgate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Noi That NKT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    {/* <ReduxPersistgate> */}
                        <NavHome />
                        <main>{children}</main>
                    {/* </ReduxPersistgate> */}
                </ReduxProvider>
            </body>
        </html>
    );
}
