import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";

import HeaderHome from "@/components/layout/header-home";
import StoreProvider from "@/app/StoreProvider";
import { StrictMode } from 'react';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Noi That NKT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider >
                    <HeaderHome />
                    <main>
                        {" "}
                        <AntdRegistry>{children}</AntdRegistry>
                    </main>
                    <StrictMode />
                </StoreProvider>

            </body>
        </html>
    );
}
